services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_NAME=database.db
      - TOKEN_SECRET_KEY=NTNv7j0TuYARvmNMmWXo6fKvM4o6nv/aUi9ryX38ZH+L1bkrnD1ObOQ8JAUmHCBq7Iy7otZcyAagBLHVKvvYaIpmMuxmARQ97jUVG16Jkpkp1wXOPsrF9zwew6TpczyHkHgX5EuLg2MeBuiT/qJACs1J0apruOOJCg/gOtkjB4c=
      - REFRESH_TOKEN_EXPIRATION_MINUTES=10080
      - TOKEN_EXPIRATION_MINUTES=60
    ports:
      - 3004:8000
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://127.0.0.1:8000/api
    ports:
      - 3005:8000
    depends_on:
      - backend
